export default {
    'common.login': 'Đăng nhập',
    'common.login.description': 'Trang quản lý dịch vụ',
    'common.logout': 'Đăng xuất',
    'common.back_home': 'Quay lại trang chủ',
    'common.back_login': 'Quay lại trang đăng nhập',
    'common.email': 'Tài khoản',
    'common.password': 'Mật khẩu',
    'common.message.copy_success': 'Sao chép thành công',
    'common.message.request_error': 'Yêu cầu không thành công',
    'common.message.request_success': 'Yêu cầu thành công',
    'common.message.request_network_error': 'Lỗi kết nối',
    'common.message.reqeust_network_error.desc': 'Mạng của bạn lỗi kết nối không thể kết nối với máy chủ',
    'common.table.no_data': 'Không có dữ liệu',
    'module.dashboard': 'Trang điều khiển',
    'module.config.system': 'Cấu hình hệ thống',
    'module.config.payment': 'Cấu hình thanh toán',
    'module.server.manage': 'Quản lý máy chủ',
    'module.server.area': 'Quản lý khu vực',
    'module.plan': 'Quản lý gói dịch vụ',
    'module.order': 'Quản lý đơn hàng',
    'module.coupon': 'Quản lý mã giảm giá',
    'module.user': 'Quản lý người dùng',
    'module.notice': 'Quản lý thông báo',
    'module.ticket': 'Quản lý đơn hỗ trợ',
    'module.knowledge': 'Quản lý hướng dẫn',
    'module.mail_log': 'Nhật ký của Email',
    'module.group.setting': 'Thiết lập',
    'module.group.server': 'Quản lý máy chủ',
    'module.group.billing': 'Quản lý đơn hàng',
    'module.group.user': 'Người dùng',
    'module.group.operation': 'Điều chỉnh',
    'module.group.index': 'Khác',
    'module.monitor_queue': 'Nhật ký máy chủ',
    'module.dashboard.month_income': 'Tổng thu nhập tháng này',
    'module.dashboard.last_month_income': 'Tổng thu nhập của tháng trước',
    'module.dashboard.month_register_total': 'Người dùng mới trong tháng này',
    'module.dashboard.ticket_pending_total': 'Phiếu hỗ trợ đang chờ xử lý',
    'module.dashboard.commission_pending_total': 'Tiền hoa hồng được xác nhận',
    'module.dashboard.server_rank': 'Xếp hạng lưu lượng máy chủ',
    'module.dashboard.user_rank': 'Xếp hạng lưu lượng người dùng',
    'module.dashboard.user_rank.list.column.email': 'Email',
    'module.dashboard.user_rank.list.column.u': 'Upload',
    'module.dashboard.user_rank.list.column.d': 'Download',
    'module.dashboard.user_rank.list.column.total': 'Tổng cộng',
    'module.dashboard.terminal_connections': 'Xếp hạng kết nối của người dùng hiện tại',
    'module.dashboard.terminal_connections.auto_refresh.on': 'Bật tự động làm mới',
    'module.dashboard.terminal_connections.auto_refresh.off': 'Tắt tự động làm mới',
    'module.dashboard.terminal_connections.list.column.email': 'Email',
    'module.dashboard.terminal_connections.list.column.connections': 'Số lượng kết nối',
    'module.dashboard.terminal_requests': 'Xếp hạng các yêu cầu kết nối của người dùng',
    'module.dashboard.terminal_requests.auto_refresh.on': 'Bật tự động làm mới',
    'module.dashboard.terminal_requests.auto_refresh.off': 'Tắt tự động làm mới',
    'module.dashboard.terminal_requests.list.column.email': 'Email',
    'module.dashboard.terminal_requests.list.column.requests': 'Số lượng yêu cầu',
    'module.dashboard.monitor_stats.warning': 'Dịch vụ hàng đợi hiện tại đang chạy bất thường, có thể khiến server không khả dụng 1 phần.',
    'module.config.system.message.sava_success': 'Đã lưu thành công',
    'module.config.system.site': 'Trang',
    'module.config.system.site.app_name': 'Tên trang web',
    'module.config.system.site.app_name.tip': 'Được sử dụng để hiển thị nơi tên trang web là cần thiết. ',
    'module.config.system.site.app_name.placeholder': 'Nhập tên trang web',
    'module.config.system.site.app_description': 'Mô tả trang web',
    'module.config.system.site.app_description.tip': 'Dùng để hiển thị nơi cần mô tả trang web.',
    'module.config.system.site.app_description.placeholder': 'Nhập mô tả trang web',
    'module.config.system.site.app_url': 'Đường dẫn (URL) trang web',
    'module.config.system.site.app_url.tip':
      'Khi hệ thống cần cung cấp một trang web ra thế giới bên ngoài, nó sẽ sử dụng các trang web của bộ phận này như thanh toán, thư tín, đẩy thông tin, v.v.',
    'module.config.system.site.app_url.placeholder': 'Nhập URL của trang web, không kết thúc bằng /',
    'module.config.system.site.subscribe_url': 'URL đăng ký',
    'module.config.system.site.subscribe_url.tip':
      'Được sử dụng để đăng ký, hãy để trống cho URL của trang web. Nếu bạn cần nhận ngẫu nhiên nhiều URL đăng ký, vui lòng sử dụng dấu phẩy để phân tách chúng.',
    'module.config.system.site.subscribe_url.placeholder':
      'Nhập URL đăng ký, không kết thúc bằng /',
    'module.config.system.site.tos_url': 'URL điều khoản người dùng',
    'module.config.system.site.tos_url.tip': 'Được sử dụng để chuyển đến điều khoản người dùng',
    'module.config.system.site.tos_url.placeholder': 'Nhâp đường link điều khoản',
    'module.config.system.site.safe_mode_enable': 'Chế độ an toàn',
    'module.config.system.site.safe_mode_enable.tip':
      'Sau khi mở, tất cả quyền truy cập vào tên miền liên kết với trang web này ngoại trừ URL của trang web sẽ là 403.',
    'module.config.system.site.stop_register': 'Ngừng đăng ký người dùng mới',
    'module.config.system.site.stop_register.tip': 'Sau khi được bật, sẽ không ai có thể đăng ký.',
    'module.config.system.site.email_verify': 'Email xác thực',
    'module.config.system.site.email_verify.tip': 'Sau khi mở, người dùng sẽ buộc phải thực hiện xác minh email.',
    'module.config.system.site.email_gmail_limit_enable': 'Cấm sử dụng nhiều bí danh trong Gmail',
    'module.config.system.site.email_gmail_limit_enable.tip': 'Sau khi bật nhiều bí danh Gmail, bạn sẽ không thể đăng ký.',
    'module.config.system.site.try_out_plan_id': 'Đăng ký dùng thử',
    'module.config.system.site.try_out_hour': 'Thời gian dùng thử (giờ)',
    'module.config.system.site.try_out_hour.tip': 'Thời gian dùng thử là 0, có nghĩa là không có giới hạn',
    'module.config.system.site.try_out_hour.placeholder': 'Vui lòng ghi thời gian dùng thử',
    'module.config.system.site.try_out_plan_id.tip':
      'Chọn gói đăng ký cần dùng thử, nếu không có tùy chọn nào bạn hãy vào phần quản lý thuê bao để thêm vào trước.',
    'module.config.system.site.try_out_plan_id.tip.placeholder': 'Chọn đăng ký dùng thử',
    'module.config.system.site.try_out_plan_id.close': 'Không',
    'module.config.system.site.email_whitelist_enable': 'Danh sách trắng email',
    'module.config.system.site.email_whitelist_enable.tip':
      'Đăng ký chỉ được phép sau khi mở danh sách email.',
    'module.config.system.site.email_whitelist': 'Danh sách trắng',
    'module.config.system.site.email_whitelist.tip': 'Vui lòng sử dụng dấu phẩy để phân tách, chẳng hạn như: yandex.com,gmail.com.',
    'module.config.system.site.email_whitelist.placeholder':
      'Vui lòng nhập hậu tố tên miền, được phân tách bằng dấu phẩy, chẳng hạn như: yandex.com,gmail.com',
    'module.config.system.site.captcha_enable': 'Xác minh Captcha',
    'module.config.system.site.captcha_enable.tip': 'Sau khi được bật, captcha của Google sẽ được sử dụng để ngăn chặn robot.',
    'module.config.system.site.captcha_key': 'Key',
    'module.config.system.site.captcha_type': 'Loại Captcha',
    'module.config.system.site.captcha_type.tip': 'Chọn nhà cung cấp Captcha',
    'module.config.system.site.recaptcha_key': 'Key Recaptcha',
    'module.config.system.site.recaptcha_key.tip': 'Khóa trong Google Recaptcha',
    'module.config.system.site.recaptcha_site_key': 'Key trang web Recaptcha',
    'module.config.system.site.recaptcha_site_key.tip': 'Key trang web đăng ký với Google',
    'module.config.system.site.recaptcha_site_key.placeholder': 'Vui lòng nhập',
    'module.config.system.site.hcaptcha_key': 'Hcaptcha',
    'module.config.system.site.hcaptcha_key.tip': 'Khóa được áp dụng trong Hcaptcha',
    'module.config.system.site.hcaptcha_key.placeholder': 'Vui lòng nhập',
    'module.config.system.site.hcaptcha_site_key': 'Key trang web Hcaptcha',
    'module.config.system.site.hcaptcha_site_key.tip': 'Key trang web được đăng ký Hcaptcha',
    'module.config.system.site.hcaptcha_site_key.placeholder': 'Vui lòng nhập',
    'module.config.system.site.recaptcha_key.placeholder': 'Vui lòng nhập',
    'module.config.system.subscribe': 'Đăng ký',
    'module.config.system.subscribe.plan_change_enable': 'Cho phép người dùng thay đổi đăng ký',
    'module.config.system.subscribe.plan_change_enable.tip': 'Sau khi mở, người dùng sẽ có thể thực hiện các thay đổi đối với gói đăng ký.',
    'module.config.system.subscribe.reset_traffic_method': 'Đặt lại dữ liệu hàng tháng',
    'module.config.system.subscribe.reset_traffic_method.tip': 'Theo mặc định, phương pháp xóa lưu lượng truy cập của người dùng là ngày 1 hàng tháng.',
    'module.config.system.subscribe.reset_traffic_method.placeholder': 'Chọn một phương pháp đặt lại đăng ký',
    'module.config.system.subscribe.reset_traffic_method.option.first_day': 'Vào ngày đầu tiên hàng tháng',
    'module.config.system.subscribe.reset_traffic_method.option.order_date': 'Ngày đặt hàng',
    'module.config.system.subscribe.reset_traffic_method.option.every_day': 'Hằng ngày',
    'module.config.system.subscribe.reset_traffic_method.option.not_reset': 'Không đặt lại dung lượng',
    'module.config.system.subscribe.rate_limit_per_minute': 'Tỷ lệ giới hạn',
    'module.config.system.subscribe.rate_limit_per_minute.tip':
      'Giới hạn yêu cầu theo phút để bảo vệ đường dẫn đăng ký',
    'module.config.system.subscribe.rate_limit_per_minute.placeholder': 'Vui lòng nhập',
    'module.config.system.subscribe.subscribe_cache_enable': 'Bật bộ nhớ đêm đường dẫn đăng ký',
    'module.config.system.subscribe.subscribe_cache_enable.tip': 
      'Khi được kích hoạt sẽ giảm tải lên máy chủ trong việc tạo các liên kết đăng ký',
    'module.config.system.invite': 'Lời mời & Ví',
    'module.config.system.invite.invite_force': 'Lời mời giới hạn',
    'module.config.system.invite.invite_force.tip': 'Sau khi mở, chỉ những người dùng được mời mới có thể đăng ký.',
    'module.config.system.invite.invite_commission': 'Phần trăm hoa hồng lời mời',
    'module.config.system.invite.invite_commission.tip': 'Tỷ lệ chia sẻ hoa hồng mặc định, bạn có thể tùy chỉnh tỷ lệ trong quản lý người dùng',
    'module.config.system.invite.invite_gen_limit': 'Người dùng có thể tạo giới hạn mã mời tối đa',
    'module.config.system.invite.invite_gen_limit.placeholder': 'Vui lòng nhập',
    'module.config.system.invite.invite_never_expire': 'Mã lời mời không bao giờ hết hạn',
    'module.config.system.invite.invite_never_expire.tip':
      'Mã mời sau khi mở sẽ không hết hạn sử dụng, ngược lại sau khi sử dụng sẽ hết giá trị.',
    'module.config.system.invite.commission_first_time_enable': 'Hoa hồng chỉ được phát cho lần đầu tiên',
    'module.config.system.invite.commission_first_time_enable.tip':
      'Sau khi mở, hoa hồng sẽ chỉ được tạo khi người được mời thanh toán lần đầu tiên và người dùng có thể được định cấu hình riêng trong phần quản lý người dùng.',
    'module.config.system.invite.commission_auto_check_enable': 'Xác nhận hoa hồng tự động',
    'module.config.system.invite.commission_auto_check_enable.tip':
      'Sau khi mở, hoa hồng sẽ tự động được xác nhận sau 3 ngày kể từ khi đơn hàng hoàn thành.',
    'module.config.system.invite.commission_withdraw_limit': 'Giới hạn cho đơn rút tiền (đ)',
    'module.config.system.invite.commission_withdraw_limit.tip': 'Các lệnh rút tiền nhỏ hơn số tiền giới hạn sẽ không được gửi.',
    'module.config.system.invite.commission_withdraw_limit.placeholder': 'Vui lòng nhập',
    'module.config.system.invite.commission_withdraw_method': 'Phương thức rút tiền',
    'module.config.system.invite.commission_withdraw_method.tip': 'Các phương thức rút tiền được hỗ trợ.',
    'module.config.system.invite.commission_withdraw_method.placeholder':
      'Vui lòng nhập hậu tố tên miền, được phân tách bằng dấu phẩy, chẳng hạn như: Momo, PayPal, Chuyển khoản',
    'module.config.system.invite.withdraw_close': 'Rút tiền',
    'module.config.system.invite.withdraw_close.tip':
      'Sau khi mở, người dùng sẽ có thể đăng ký rút tiền hoa hồng lời mời sẽ được cộng trực tiếp vào số dư của người dùng.',
    'module.config.system.invite.transfer_balance_close': 'Đóng chuyển tiền',
    'module.config.system.invite.transfer_balance_close.tip':
         'Sau khi đóng, việc chuyển số dư giữa những người dùng sẽ bị vô hiệu hóa',
    'module.config.system.invite.min_recharge_amount': 'Số tiền nạp tối thiểu',
    'module.config.system.invite.min_recharge_amount.placeholder': 'Vui lòng nhập',
    'module.config.system.invite.max_recharge_amount': 'Số tiền nạp tối đa',
    'module.config.system.invite.max_recharge_amount.placeholder': 'Vui lòng nhập',
    'module.config.system.frondend': 'Giao diện',
    'module.config.system.frondend.warning':
      'Nếu bạn triển khai V2board theo một cách riêng biệt, cấu hình trên trang này sẽ không có hiệu lực.',
    'module.config.system.frondend.frontend_theme': 'Chủ đề',
    'module.config.system.frondend.frontend_theme.tip':
      'Chủ đề phía người dùng, các chủ đề mới có thể được tải lên thư mục public/theme để gọi',
    'module.config.system.frondend.frontend_admin_path': 'Đường dẫn nền',
    'module.config.system.frondend.frontend_admin_path.tip':
      'Đường dẫn giao diện quản lý hậu trường, sau khi sửa đổi, đường dẫn quản trị ban đầu sẽ được thay đổi',
    'module.config.system.frondend.light': 'Sáng',
    'module.config.system.frondend.dark': 'Tối',
    'module.config.system.frondend.frontend_theme_sidebar': 'Kiểu thanh bên',
    'module.config.system.frondend.frontend_theme_header': 'Kiểu thanh đầu',
    'module.config.system.frondend.frontend_theme_color': 'Màu chủ đề',
    'module.config.system.frondend.frontend_theme_color.option.default': 'Mặc định',
    'module.config.system.frondend.frontend_theme_color.option.black': 'Tối',
    'module.config.system.frondend.frontend_theme_color.option.darkblue': 'Xanh tối',
    'module.config.system.frondend.frontend_theme_color.option.green': 'Xanh lá nhạt',
    'module.config.system.frondend.frontend_background_url': 'Hình nền',
    'module.config.system.frondend.frontend_background_url.tip': 'Sẽ được hiển thị trên trang đăng nhập.',
    'module.config.system.frondend.frontend_world_fill_color': 'Bản đồ điền màu',
    'module.config.system.frondend.frontend_world_fill_color.tip': 'Sẽ hiển thị xem trước trên trang chủ',
    'module.config.system.frondend.frontend_world_marker_color': 'Màu đánh dấu bản đồ',
    'module.config.system.frondend.frontend_world_marker_color.tip': 'Được sử dụng để gắn nhãn các nút trong bản đồ',
    'module.config.system.frondend.frontend_customer_service_method': 'Hệ thống dịch vụ khách hàng của bên thứ ba',
    'module.config.system.frondend.frontend_customer_service_method.tip': 'Hệ thống dịch vụ khách hàng bên ngoài được chỉ định',
    'module.config.system.frondend.frontend_customer_service_method.option.close': 'Không',
    'module.config.system.frondend.frontend_customer_service_method.option.crisp': 'Crisp',
    'module.config.system.frontend.frontend_customer_service_id': 'Mã ID',
    'module.config.system.frontend.frontend_customer_service_id.tip':
      'Chuỗi ký tự do hệ thống dịch vụ khách hàng cung cấp để nhận dạng bạn',
    'module.config.system.frontend.frontend_customer_service_id.placeholder': 'Vui lòng nhập',
    'module.config.system.server': 'Server',
    'module.config.system.server.server_token': 'Khóa giao tiếp',
    'module.config.system.server.server_token.tip':
      'Chìa khóa giao tiếp giữa V2board và máy chủ để người khác không lấy được dữ liệu.',
    'module.config.system.server.server_token.placeholder': 'Vui lòng nhập',
    'module.config.system.email': 'Email',
    'module.config.system.email.warning':
      'Nếu bạn thay đổi cấu hình trên trang này, bạn cần khởi động lại dịch vụ hàng đợi. Ngoài ra, ưu tiên cấu hình của trang này cao hơn cấu hình thư trong .env。',
    'module.config.system.email.email_host': 'Địa chỉ máy chủ SMTP',
    'module.config.system.email.email_host.tip': 'Địa chỉ dịch vụ do nhà cung cấp dịch vụ email cung cấp',
    'module.config.system.email.email_host.placeholder': 'Vui lòng nhập',
    'module.config.system.email.email_port': 'Cổng dịch vụ SMTP',
    'module.config.system.email.email_port.tip': 'Các cổng thông dụng là 25, 465, 587',
    'module.config.system.email.email_port.placeholder': 'Vui lòng nhập',
    'module.config.system.email.email_encryption': 'Phương thức mã hóa SMTP',
    'module.config.system.email.email_encryption.tip':
      'Phương pháp mã hóa SMTP Phương pháp mã hóa cổng 465 nói chung là SSL, phương pháp mã hóa cổng 587 nói chung là TLS',
    'module.config.system.email.email_encryption.placeholder': 'Vui lòng nhập',
    'module.config.system.email.email_username': 'Tài khoản SMTP',
    'module.config.system.email.email_username.tip': 'Tài khoản do nhà cung cấp dịch vụ email cung cấp',
    'module.config.system.email.email_username.placeholder': 'Vui lòng nhập',
    'module.config.system.email.email_password': 'Mật khẩu SMTP',
    'module.config.system.email.email_password.tip': 'Mật khẩu do nhà cung cấp dịch vụ email cung cấp',
    'module.config.system.email.email_password.placeholder': 'Vui lòng nhập',
    'module.config.system.email.email_from_address': 'Địa chỉ người gửi',
    'module.config.system.email.email_from_address.tip': 'Địa chỉ gửi thư do nhà cung cấp dịch vụ thư cung cấp',
    'module.config.system.email.email_from_address.placeholder': 'Vui lòng nhập',
    'module.config.system.email.email_template': 'Mẫu thư',
    'module.config.system.email.email_template.tip': 'Bạn có thể xem cách tùy chỉnh mẫu email trong tài liệu',
    'module.config.system.email.email_template.placeholder': 'Vui lòng chọn',
    'module.config.system.email.email_rate_limit': 'Giới hạn tần suất gửi',
    'module.config.system.email.email_rate_limit.tip':
      'Một số nhà cung cấp dịch vụ SMTP giới hạn tần suất gửi, bạn có thể kiểm soát tần suất gửi tại đây, đơn vị là (lần / phút), sau khi sửa đổi, bạn cần khởi động lại hàng đợi để có hiệu lực',
    'module.config.system.email.email_rate_limit.placeholder': 'Vui lòng nhập',
    'module.config.system.email.test_send_mail': 'Gửi email thử nghiệm',
    'module.config.system.email.test_send_mail.tip': 'Email sẽ được gửi đến hộp thư của người dùng hiện đang đăng nhập',
    'module.config.system.email.test_send_mail.btn': 'Kiểm tra nhanh',
    'module.config.system.email.test_send_mail.message.success': 'Kiểm tra email thành công',
    'module.config.system.telegram': 'Telegram',
    'module.config.system.telegram.telegram_bot_enable': 'Bật thông báo tự động',
    'module.config.system.telegram.telegram_bot_enable.tip':
      'Sau khi được bật, bot sẽ cung cấp các thông báo cơ bản cho quản trị viên và người dùng, những người bị ràng buộc với điện tín.',
    'module.config.system.telegram.telegram_bot_token': 'Mã Token',
    'module.config.system.telegram.telegram_bot_token.tip': 'Vui lòng nhập mã token được cung cấp bởi Botfather.',
    'module.config.system.telegram.telegram_set_webhook': 'Thiết lập webhook',
    'module.config.system.telegram.telegram_set_webhook.tip':
      'Đặt webhook cho bot. Nếu không đặt, bạn sẽ không thể nhận thông báo Telegram.',
    'module.config.system.telegram.telegram_set_webhook.btn': 'Đồng bộ Webhook',
    'module.config.system.telegram.telegram_set_webhook.message.success': 'Webhook được thiết lập thành công',
    'module.config.system.telegram.telegram_discuss_link': 'Đường dẫn của nhóm Telegram',
    'module.config.system.telegram.telegram_discuss_link.tip': 'Sau khi điền, nó sẽ được hiển thị ở phía người dùng, hoặc được sử dụng khi cần thiết',
    'module.config.payment.add_btn': 'Thêm phương thức thanh toán',
    'module.config.payment.list.column.id': 'ID',
    'module.config.payment.list.column.enable': 'Bật/Tắt',
    'module.config.payment.list.column.name': 'Tên',
    'module.config.payment.list.column.payment': 'Giao diện thanh toán',
    'module.config.payment.list.column.notify_url': 'Địa chỉ thông báo',
    'module.config.payment.list.column.notify_url.tip':
      'Cổng thanh toán sẽ thông báo dữ liệu đến địa chỉ này, vui lòng để địa chỉ này thông qua tường lửa.',
    'module.config.payment.list.column.action': 'Cấu hình',
    'module.config.payment.list.column.action.edit': 'Chỉnh sửa',
    'module.config.payment.list.column.action.drop': 'Xoá',
    'module.config.payment.list.column.action.drop.message.success': 'Đã xóa thành công',
    'module.config.payment.list.modal.name': 'Tên',
    'module.config.payment.list.modal.name.placeholder': 'Để sử dụng màn hình giao diện chính',
    'module.config.payment.list.modal.payment': 'Giao diện',
    'module.config.payment.list.modal.payment.placeholder': 'Vui lòng chọn',
    'module.config.payment.list.modal.icon_type': 'Biểu tượng',
    'module.config.payment.list.modal.icon_type.placeholder': 'Xin vui lòng chọn',
    'module.config.payment.list.modal.notify_domain': 'Tên miền thông báo tùy chỉnh',
    'module.config.payment.list.modal.notify_domain.placeholder': 'Không bắt buộc, mặc định là tên miền trang web',
    'module.config.payment.list.edit.modal.title': 'Chỉnh sửa phương thức thanh toán',
    'module.config.payment.list.edit.message.success': 'Đã lưu thành công',
    'module.config.payment.list.add.modal.title': 'Thêm phương thức thanh toán',
    'module.config.payment.list.add.modal.ok_btn': 'Thêm',
    'module.config.payment.list.add.modal.cancel_btn': 'Hủy bỏ',
    'module.config.payment.list.add.message.success': 'Thêm thành công',
    'module.server.manage.search.placeholder': 'Tìm kiếm',
    'module.server.manage.save_sort_btn': 'Lưu sắp xếp',
    'module.server.manage.save_sort.message.success': 'Lưu và sắp xếp thành công',
    'module.server.manage.list.column.action': 'Tuỳ chọn',
    'module.server.manage.list.column.action.drop': 'Xóa bỏ',
    'module.server.manage.list.column.action.drop.message.success': 'Đã xóa thành công',
    'module.server.manage.list.column.action.copy.message.success': 'Sao chép thành công',
    'module.server.manage.list.column.action.edit': 'Chỉnh sửa',
    'module.server.manage.list.column.action.copy': 'Sao chép',
    'module.server.manage.list.column.action.btn': 'Tuỳ chọn',
    'module.server.manage.list.column.id': 'ID',
    'module.server.manage.list.column.show': 'Bật/Tắt',
    'module.server.manage.list.column.check': 'Kiểm tra',
    'module.server.manage.list.column.name': 'Tên',
    'module.server.manage.list.column.name.tip.error': 'Không chạy',
    'module.server.manage.list.column.name.tip.warning': 'Không ai sử dụng hoặc máy chủ báo cáo một ngoại lệ',
    'module.server.manage.list.column.name.tip.processing': 'Chạy bình thường',
    'module.server.manage.list.column.address': 'Địa chỉ',
    'module.server.manage.list.column.online': 'Số lượng người hoạt động',
    'module.server.manage.list.column.online.tip': 'Nó phụ thuộc vào tần suất báo cáo của máy chủ. Định dạng: số người thực tế (loại bỏ trùng lặp) / tổng số bản ghi',
    'module.server.manage.list.column.rate': 'Tỷ lệ',
    'module.server.manage.list.column.rate.tip': 'Tốc độ Download và Upload được sử dụng sẽ được trừ đi bằng cách nhân với tỷ lệ đã đặt',
    'module.server.manage.list.column.plan': 'Gói đăng ký',
    'common.modal.server.area.create_title': 'Tạo khu vực',
    'common.modal.server.area.edit_title': 'Chỉnh sửa khu vực',
    'common.modal.server.area.flag': 'Quốc kỳ',
    'common.modal.server.area.flag.placeholder': 'Vui lòng nhập biểu tượng Emoji',
    'common.modal.server.area.country': 'Quốc gia',
    'common.modal.server.area.country.placeholder': 'Vui lòng nhập',
    'common.modal.server.area.city': 'Thành phố',
    'common.modal.server.area.city.placeholder': 'Vui lòng nhập',
    'common.modal.server.area.country_code': 'Mã quốc gia',
    'common.modal.server.area.country_code.placeholder': 'Vui lòng nhập',
    'common.modal.server.area.lng': 'Kinh độ',
    'common.modal.server.area.lng.placeholder': 'Vui lòng nhập',
    'common.modal.server.area.lat': 'Vĩ độ',
    'common.modal.server.area.lat.placeholder': 'Vui lòng nhập',
    'common.modal.server.area.message.create_success': 'Đã tạo thành công',
    'common.modal.server.area.message.edit_success': 'Đã chỉnh sửa thành công',
    'common.message.create_success': 'Đã tạo thành công',
    'common.message.edit_success': 'Chỉnh sửa thành công',
    'module.server.manage.drawer.add_title': 'Tạo máy chủ mới',
    'module.server.manage.drawer.edit_title': 'Chỉnh sửa máy chủ',
    'module.server.manage.message.edit_success': 'Chỉnh sửa thành công',
    'module.server.manage.message.create_success': 'Đã tạo thành công',
    'module.server.manage.drawer.ok_btn': 'OK',
    'module.server.manage.drawer.cancel_btn': 'Huỷ bỏ',
    'module.server.manage.name': 'Tên máy chủ',
    'module.server.manage.name.placeholder': 'Vui lòng nhập tên máy chủ',
    'module.server.manage.rate': 'Tỷ lệ phóng đại',
    'module.server.manage.area_id': 'Khu vực',
    'module.server.manage.area_id.placeholder': 'Vui lòng chọn một khu vực',
    'module.server.manage.plan_id': 'Gói đăng ký',
    'module.server.manage.plan_id.placeholder': 'Vui lòng chọn gói đăng ký',
    'module.server.manage.tags': 'Nhãn',
    'module.server.manage.tags.placeholder': 'Sau khi nhập, nhấn Enter để thêm thẻ',
    'module.server.manage.ips': 'Load IP',
    'module.server.manage.ips.placeholder': 'Nhập và nhấn Enter để thêm IP',
    'module.server.manage.ips.tip': 'Hệ thống sẽ theo dõi trạng thái IP đang chạy',
    'module.server.manage.host': 'Địa chỉ domain',
    'module.server.manage.host.placeholder': 'Địa chỉ hoặc IP',
    'module.server.manage.port': 'Cổng kết nối',
    'module.server.manage.port.placeholder': 'Cổng kết nối người dùng',
    'module.server.manage.server_port': 'Cổng dịch vụ',
    'module.server.manage.server_port.placeholder': 'Cổng mở máy chủ',
    'module.server.manage.shadowsocks.cipher': 'Thuật toán mã hóa',
    'module.server.manage.shadowsocks.cipher.placeholder': 'Xin vui lòng chọn',
    'module.server.manage.parent_id': 'Cổng chuyển tiếp',
    'module.server.manage.parent_id.extra_link': 'Thêm câu trả lời',
    'module.server.manage.parent_id.placeholder': 'Xin vui lòng chọn',
    'module.server.manage.parent_id.option.default': 'Không có',
    'module.server.manage.trojan.allow_insecure': 'Cho phép không an toàn',
    'module.server.manage.trojan.allow_insecure.option.off': 'Không',
    'module.server.manage.trojan.allow_insecure.option.on': 'Có',
    'module.server.manage.trojan.server_name': 'Thiết lập máy chủ (SNI)',
    'module.server.manage.trojan.server_name.placeholder': 'Được sử dụng để xác minh chứng chỉ khi địa chỉ nút không phù hợp với chứng chỉ',
    'module.server.manage.vmess.tls': 'TLS',
    'module.server.manage.vmess.tls.tip': 'TLS hỗ trợ trước tiên cần có trong VPN/root/.server.crt và server.key',
    'module.server.manage.vmess.tls.option.off': 'Không hỗ trợ',
    'module.server.manage.vmess.tls.option.on': 'Có hỗ trợ',
    'module.server.manage.vmess.tls_settings.drawer.title': 'Chỉnh sửa cấu hình TLS',
    'module.server.manage.vmess.tls_settings.server_name': 'Biệt hiệu máy chủ',
    'module.server.manage.vmess.tls_settings.server_name.placeholder': 'Vui lòng để trống nếu không sử dụng',
    'module.server.manage.vmess.tls_settings.allow_insecure': 'Cho phép không an toàn',
    'module.server.manage.vmess.server_port.placeholder': 'Không phải NAT cùng một cổng kết nối',
    'module.server.manage.common.network': 'Giao thức chuyển giao',
    'module.server.manage.common.network.placeholder': 'Chọn giao thức truyền',
    'module.server.manage.common.network.option.0': 'không được thiết lập',
    'module.server.manage.common.network_settings.drawer.title': 'Chỉnh sửa cấu hình giao thức',
    'module.server.manage.common.network_settings.editor.placeholder': 'Vui lòng nhập các mục cấu hình JSON tại đây',
    'module.server.manage.vmess.rule_settings': 'Quy tắc kiểm toán',
    'module.server.manage.vmess.rule_settings.tip': 'Quyền truy cập trong các quy tắc sẽ bị từ chối',
    'module.server.manage.vmess.rule_settings.edit_btn': 'Chỉnh sửa quy tắc',
    'module.server.manage.vmess.rule_settings.drawer.title': 'Chỉnh sửa cấu hình kiểm tra',
    'module.server.manage.vmess.dns_settings': 'Quy tắc DNS',
    'module.server.manage.vmess.dns_settings.edit_btn': 'Chỉnh sửa quy tắc DNS',
    'module.server.manage.vmess.dns_settings.drawer.title': 'Chỉnh sửa cấu hình DNS',
    'module.server.manage.vmess.dns_settings.domain': 'Bộ lọc miền',
    'module.server.manage.vmess.dns_settings.protocol': 'Bộ lọc giao thức',
    'module.server.manage.vmess.dns_settings.drawer.sub_title': 'Bảng máy chủ DNS',
    'module.server.manage.vmess.dns_settings.name': 'Nhóm máy chủ',
    'module.server.manage.vmess.dns_settings.address': 'Địa chỉ máy chủ DNS',
    'module.server.manage.vmess.dns_settings.address.placeholder': 'Nhập địa chỉ máy chủ DNS',
    'module.server.manage.vmess.dns_settings.port': 'Port',
    'module.server.manage.vmess.dns_settings.port.placeholder': 'Port',
    'module.server.manage.vmess.dns_settings.domains': 'Tên miền',
    'module.server.manage.vmess.dns_settings.domains.placeholder':
      'Danh sách tên miền. Các tên miền có trong danh sách này sẽ được máy chủ này truy vấn đầu tiên.',
    'module.server.manage.vmess.dns_settings.add_btn': 'Thêm',
    'module.server.area.add_btn': 'Thêm khu vực',
    'module.server.area.list.column.id': 'ID khu vực',
    'module.server.area.list.column.flag': 'Cờ quốc gia',
    'module.server.area.list.column.country': 'Quốc gia',
    'module.server.area.list.column.city': 'Thành phố',
    'module.server.area.list.column.country_code': 'Mã quốc gia',
    'module.server.area.list.column.lng': 'Kinh độ',
    'module.server.area.list.column.lat': 'Vĩ độ',
    'module.server.area.list.column.action': 'Tùy chỉnh',
    'module.server.area.list.column.action.edit': 'Sửa',
    'module.server.area.list.column.action.drop': 'Xóa',
    'module.server.area.list.message.drop_success': 'Đã xóa thành công',
    'module.notice.add_btn': 'Thêm thông báo',
    'module.notice.list.column.id': '#',
    'module.notice.list.column.title': 'Tiêu đề',
    'module.notice.list.column.created_at': 'Thời gian tạo',
    'module.notice.list.column.action': 'Tuỳ chọn',
    'module.notice.list.column.action.edit': 'Chỉnh sửa',
    'module.notice.list.column.action.drop': 'Xóa bỏ',
    'module.notice.drawer.edit_title': 'Chỉnh sửa thông báo',
    'module.notice.drawer.create_title': 'Tạo thông báo mới',
    'module.notice.drawer.title': 'Tiêu đề',
    'module.notice.drawer.title.placeholder': 'Nhập tiêu đề thông báo',
    'module.notice.drawer.content': 'Nội dung thông báo',
    'module.notice.drawer.content.placeholder': 'Nhập nội dung thông báo',
    'module.notice.drawer.img_url': 'URL hình ảnh',
    'module.notice.drawer.img_url.placeholder': 'Nhập URL hình ảnh',
    'module.notice.drawer.message.add_success': 'Thêm thành công',
    'module.notice.drawer.message.edit_success': 'Chỉnh sửa thành công',
    'module.notice.drawer.ok_btn': 'OK',
    'module.notice.drawer.cancel_btn': 'Hủy bỏ',
    'module.notice.list.column.action.drop.message.success': 'Đã xóa thành công',
    'module.knowledge.add_btn': 'Thêm kiến ​​thức cơ bản',
    'module.knowledge.list.column.action': 'Tuỳ chọn',
    'module.knowledge.list.column.action.btn': 'Tuỳ chọn',
    'module.knowledge.list.column.action.drop': 'Xóa bỏ',
    'module.knowledge.list.column.action.drop.message.success': 'Đã xóa thành công',
    'module.knowledge.list.column.action.edit': 'Chỉnh sửa',
    'module.knowledge.list.column.show': 'Bật/Tắt',
    'module.knowledge.list.column.free': 'Hiện khi chưa đăng ký',
    'module.knowledge.list.column.free.tip': 'Người dùng có thể xem nội dung dù chưa đăng ký dịch vụ',
    'module.knowledge.list.column.title': 'Tiêu đề',
    'module.knowledge.list.column.category': 'Phân loại',
    'module.knowledge.list.column.updated_at': 'Lần cuối chỉnh sửa',
    'module.knowledge.save_sort_btn': 'Lưu sắp xếp',
    'module.knowledge.save_sort.message.success': 'Lưu và sắp xếp thành công',
    'module.knowledge.drawer.edit_title': 'Chỉnh sửa kiến ​​thức cơ bản',
    'module.knowledge.drawer.add_title': 'Thêm kiến thức cơ bản',
    'module.knowledge.message.edit_success': 'Chỉnh sửa thành công',
    'module.knowledge.message.create_success': 'Đã tạo thành công',
    'module.knowledge.drawer.ok_btn': 'OK',
    'module.knowledge.drawer.cancel_btn': 'Huỷ bỏ',
    'module.knowledge.title': 'Tiêu đề',
    'module.knowledge.title.placeholder': 'Nhập tiêu đề',
    'module.knowledge.category': 'Phân loại',
    'module.knowledge.category.placeholder': 'Nhập phân loại, phân loại sẽ được sắp xếp',
    'module.knowledge.language': 'Ngôn ngữ',
    'module.knowledge.language.placeholder': 'Chọn ngôn ngữ kiến thức',
    'module.knowledge.language.option.chinese': '中文',
    'module.knowledge.language.option.english': 'English',
    'module.knowledge.language.option.vietnamese': 'Tiếng Việt',
    'module.knowledge.body': 'Nội dung',
    'module.plan.save_sort.message.success': 'Lưu và sắp xếp thành công',
    'module.plan.add_btn': 'Thêm gói dịch vụ',
    'module.plan.save_sort_btn': 'Lưu sắp xếp',
    'module.plan.list.column.action': 'Tuỳ chọn',
    'module.plan.list.column.action.btn': 'Tuỳ chọn',
    'module.plan.list.column.action.edit': 'Chỉnh sửa',
    'module.plan.list.column.action.drop': 'Xóa bỏ',
    'module.plan.list.column.action.drop.message.success': 'Đã xóa thành công',
    'module.plan.list.column.id': 'ID',
    'module.plan.list.column.show': 'Bật/Tắt gói',
    'module.plan.list.column.renew': 'Gia hạn',
    'module.plan.list.column.renew.tip': 'Người dùng đã mua gói có thể được gia hạn khi gói dịch vụ ngừng bán không?',
    'module.plan.list.column.name': 'Tên gói',
    'module.plan.list.column.user_count': 'Số người dùng',
    'module.plan.list.column.user_count.tip': 'Người dùng hiện tại / Người dùng cũ',
    'module.plan.list.column.server_count': 'Số lượng máy chủ',
    'module.plan.list.column.transfer_enable': 'Dung Lượng',
    'module.plan.drawer.message.edit_success': 'Chỉnh sửa thành công',
    'module.plan.drawer.message.create_success': 'Thành công',
    'module.plan.drawer.edit_title': 'Chỉnh sửa gói dịch vụ',
    'module.plan.drawer.create_title': 'Tạo gói dịch vụ',
    'module.plan.drawer.name': 'Tên gói',
    'module.plan.drawer.name.placeholder': 'Nhập tên gói',
    'module.plan.drawer.content': 'Mô tả gói',
    'module.plan.drawer.content.placeholder': 'Vui lòng nhập mô tả gói, HTML được hỗ trợ',
    'module.plan.drawer.setting_price': 'Giá tiền/Tùy Chỉnh',
    'module.plan.drawer.setting_price.tips': 'Để trống số tiền sẽ không mở bán',
    'module.plan.drawer.transfer_enable': 'Thêm GB cho gói',
    'module.plan.drawer.transfer_enable.placeholder': 'Vui lòng nhập số GB',
    'module.plan.drawer.time_limit': 'Giới hạn thời gian',
     'module.plan.drawer.time_limit.placeholder': 'Vui lòng chọn có bật giới hạn thời gian không?',
     'module.plan.drawer.time_range': 'Thời gian giới hạn',
     'module.plan.drawer.time_limit.option.on': 'Bật',
     'module.plan.drawer.time_limit.option.off': 'Tắt',
    'module.plan.drawer.allow_ids': 'Điều kiện mua gói',
    'module.plan.drawer.allow_ids.tips':
      'Để mua gói dịch vụ, trước tiên người dùng phải đáp ứng các điều kiện mua và gói hiện tại là gói đủ điều kiện để mua được gói này',
    'module.plan.drawer.allow_ids.placeholder': 'Vui lòng chọn một gói dịch vụ đã có trong hệ thống',
    'module.plan.drawer.reset_traffic_method': 'Phương thức đặt lại dung lượng',
    'module.plan.drawer.reset_traffic_method.placeholder': 'Chọn kiểu đặt lại dung lượng',
    'moudle.plan.drawer.reset_traffic_method.option.system': 'Theo hệ thống',
    'moudle.plan.drawer.reset_traffic_method.option.month_first_day': 'Ngày đầu tiên của tháng',
    'moudle.plan.drawer.reset_traffic_method.option.order_day': 'Đặt lại ngày đặt hàng',
    'moudle.plan.drawer.reset_traffic_method.option.every_day': 'Đặt lại dung lượng hằng ngày',
    'moudle.plan.drawer.reset_traffic_method.option.not_reset': 'Không đặt lại',
    'module.plan.drawer.edit.ok_btn': 'Thực hiện',
    'module.plan.drawer.edit.cancel_btn': 'Hủy bỏ',
    'module.plan.drawer.price.title': 'Chỉnh sửa giá gói dịch vụ',
    'module.plan.drawer.price.add_btn': 'Thêm tùy chỉnh',
    'module.plan.drawer.price.package': 'Tùy chỉnh gói',
    'module.plan.drawer.price.name': 'Tên gói',
    'module.plan.drawer.price.name.month_price': 'Một tháng',
    'module.plan.drawer.price.name.quarter_price': 'Ba tháng',
    'module.plan.drawer.price.name.half_year_price': 'Nửa năm',
    'module.plan.drawer.price.name.year_price': 'Một năm',
    'module.plan.drawer.price.name.two_year_price': 'Hai năm',
    'module.plan.drawer.price.name.three_year_price': 'Ba năm',
    'module.plan.drawer.price.name.onetime_price': 'Vĩnh viễn',
    'module.plan.drawer.price.name.reset_price': 'Mua thêm dung lượng',
    'module.plan.drawer.price.name.placeholder': 'Bắt buộc, vui lòng nhập',
    'module.plan.drawer.price.value': 'Giá bán',
    'module.plan.drawer.price.value.placeholder': 'Bắt buộc, vui lòng nhập',
    'module.plan.drawer.price.off_tip': 'Gợi ý giảm giá',
    'module.plan.drawer.price.off_tip.placeholder': 'Vui lòng nhập (Không bắt buộc)',
    'module.plan.drawer.price.tip': 'Đề xuất',
    'module.plan.drawer.price.tip.placeholder': 'Tùy chọn, vui lòng nhập',
    'module.plan.drawer.price.type': 'Chu kỳ của gói',
    'module.plan.drawer.price.type.placeholder': 'Vui lòng chọn',
    'module.plan.drawer.price.type.option.loop_time': 'Gói có thời hạn sử dụng',
    'module.plan.drawer.price.type.option.one_time': 'Vĩnh viễn',
    'module.plan.drawer.price.type.option.reset': 'Mua thêm dung lượng',
    'module.plan.drawer.price.expire_type': 'Chu kỳ sử dụng gói',
    'module.plan.drawer.price.expire_type.placeholder': 'Xin vui lòng chọn',
    'module.plan.drawer.price.expire_type.option.day': 'Ngày',
    'module.plan.drawer.price.expire_type.option.month': 'Tháng',
    'module.plan.drawer.price.expire_type.option.year': 'Năm',
    'module.plan.drawer.price.expire_value': 'Ngày/Tháng/Năm hãy nhập số',
    'module.plan.drawer.price.expire_value.placeholder': 'Vui lòng nhập giá trị',
    'module.ticket.status.on': 'Đang mở',
    'module.ticket.status.off': 'Đã đóng',
    'module.ticket.list.column.id': '#',
    'module.ticket.list.column.subject': 'Chủ đề',
    'module.ticket.list.column.level': 'Mức độ',
    'module.ticket.list.column.level.low': 'Thấp',
    'module.ticket.list.column.level.medium': 'Trung bình',
    'module.ticket.list.column.level.high': 'Cao',
    'module.ticket.list.column.reply_status': 'Tình trạng phiếu hỗ trợ',
    'module.ticket.list.column.reply_status.replied': 'Đã trả lời',
    'module.ticket.list.column.reply_status.to_be_replied': 'Đợi trả lời',
    'module.ticket.list.column.created_at': 'Thời gian tạo',
    'module.ticket.list.column.updated_at': 'Lần cuối trả lời',
    'module.ticket.list.column.action': 'Tuỳ chọn',
    'module.ticket.list.column.action.view': 'Xem',
    'module.ticket.list.column.action.close': 'Đóng',
    'module.ticket.message.close_success': 'Đã đóng thành công',
    'module.ticket.detail.user': 'Người dùng',
    'module.ticket.detail.enter_message': 'Nhập nội dung để trả lời phiếu hỗ trợ ...',
    'module.user.filter_btn': 'Lọc',
    'module.user.show_column_btn': 'Hiển thị các cột',
    'module.user.show_column.title': 'Quản lý cột hiển thị',
    'module.user.show_column.message.success': 'Thao tác thành công',
    'module.user.suspend.title': 'Tạm ngưng người dùng',
    'module.user.suspend.email': 'Email người dùng',
    'module.user.suspend.duration': 'Khoảng thời gian',
    'module.user.suspend.duration.placeholder': 'Xin vui lòng chọn',
    'module.user.suspend.duration.option.five_min': 'Năm phút',
    'module.user.suspend.duration.option.fifteen_min': 'Mười lăm phút',
    'module.user.suspend.duration.option.half_hour': 'Nửa tiếng',
    'module.user.suspend.duration.option.one_hour': 'Một tiếng',
    'module.user.suspend.notify': 'Thông báo đến người dùng?',
    'module.user.suspend.notify.placeholder': 'Xin vui lòng chọn',
    'module.user.suspend.notify.option.on': 'Có',
    'module.user.suspend.notify.option.off': 'Không',
    'module.user.suspend.message.success': 'Tạm ngưng tài khoản thành công',
    'module.user.action_btn': 'Tuỳ chọn',
    'module.user.action.tip': 'Tips：Bạn có thể sử dụng bộ lọc để lọc và sau đó sử dụng các hành động để thao tác trên những người dùng được lọc.',
    'module.user.action.export_csv': 'Xuất CSV',
    'module.user.action.send_email': 'Gửi email',
    'module.user.action.batch_ban': 'Cấm hàng loạt',
    'module.user.list.column.action': 'Tuỳ chọn',
    'module.user.list.column.action.edit': 'Chỉnh sửa',
    'module.user.list.column.action.drop': 'Xóa bỏ',
    'module.user.list.column.action.suspend': 'Tạm ngưng',
    'module.user.list.column.action.recovery': 'Hồi phục',
    'module.user.list.column.action.assign_order': 'Gán đơn hàng',
    'module.user.list.column.action.copy_url': 'Sao chép URL đăng ký',
    'module.user.list.column.action.reset_secret': 'Đặt lại UUID và URL đăng ký',
    'module.user.list.column.action.user_order': 'Đơn hàng đã mua',
    'module.user.list.column.action.user_invite': 'Lời mời đã gửi',
    'module.user.list.column.id': 'ID',
    'module.user.list.column.email': 'Email',
    'module.user.list.column.remarks': 'Nhận xét',
    'module.user.list.column.plan_id': 'Gói đăng ký',
    'module.user.list.column.t': 'Trực tuyến',
    'module.user.list.column.t.tip': 'Trực tuyến của người dùng cập nhật mỗi nửa tiếng',
    'module.user.list.column.total_used': 'Đã sử dụng',
    'module.user.list.column.u': 'Tải lên',
    'module.user.list.column.d': 'Tải xuống',
    'module.user.list.column.banned': 'Tình trạng tài khoản',
    'module.user.list.column.banned.off': 'Bình thường',
    'module.user.list.column.banned.on': 'Ban',
    'module.user.list.column.banned.recovery_time.tooltip': 'Thời gian mở khóa: {time}',
    'module.user.list.column.transfer_enable_value': 'Dung lượng',
    'module.user.list.column.invite_total': 'Số lượng người được mời',
    'module.user.list.column.order_amount_total': 'Tổng số tiền kiếm được',
    'module.user.list.column.expired_at': 'Hạn sử dụng',
    'module.user.list.column.expired_at.nerver_expire': 'Vĩnh viễn',
    'module.user.list.column.created_at': 'Thời gian đăng ký',
    'module.user.list.column.updated_at': 'Hoạt động cuối cùng',
    'module.user.list.column.last_login_at': 'Lần đăng nhập cuối cùng',
    'module.user.list.column.last_login_ip': 'IP Đăng nhập lần cuối',
    'module.user.list.column.is_admin': 'Quản trị viên',
    'module.user.list.column.register_ip': 'IP Đăng ký',
    'module.user.action.send_email.modal.title': 'Gửi email',
    'module.user.action.send_email.subject': 'Chủ đề email',
    'module.user.action.send_email.subject.placeholder': 'Nhập chủ đề của email',
    'module.user.action.send_email.content': 'Nội dung',
    'module.user.action.send_email.content.placeholder': 'Nhập nội dung tin nhắn',
    'module.user.action.send_email.addressee': 'Người nhận',
    'module.user.action.send_email.addressee.option.all': 'Tất cả người dùng',
    'module.user.action.send_email.addressee.option.filter': 'Lọc người dùng',
    'module.user.action.send_email.message.success': 'Đã được thêm vào hàng đợi',
    'module.user.action.generate.title': 'Tạo tài khoản',
    'module.user.action.generate.email': 'Email',
    'module.user.action.generate.email.prefix.placeholder': 'Tài khoản (để trống để tạo bất kì)',
    'module.user.action.generate.email.suffix.placeholder': 'Đuôi email',
    'module.user.action.generate.password': 'Mật khẩu',
    'module.user.action.generate.password.placeholder': 'Để trống, mật khẩu giống email',
    'module.user.action.generate.expired_at': 'Hạn sử dụng',
    'module.user.action.generate.expired_at.placeholder': 'Chọn ngày hết hạn của người dùng, để trống sẽ không giới hạn thời gian hết hạn!',
    'module.user.drawer.edit.order_day': 'Ngày đặt hàng',
    'module.user.drawer.edit.order_day.tip': 'Hệ thống mặc định tạo theo thứ tự thực tế (vui lòng sửa đổi theo tình hình thực tế)',
    'module.user.drawer.edit.order_day.placeholder': 'Vui lòng nhập: [1-31]',
    'module.user.action.generate.plan_id': 'Gói đăng ký',
    'module.user.action.generate.plan_id.option.none': 'Không',
    'module.user.action.generate.count': 'Số lượng người',
    'module.user.action.generate.count.placeholder': 'Nếu đó là tạo hàng loạt, vui lòng nhập số lượng',
    'module.user.action.generate.message.success': 'Tạo người dùng thành công',
    'module.user.action.filter.drawer.title': 'Lọc',
    'module.user.action.filter.drawer.ok_btn': 'Tìm kiếm',
    'module.user.action.filter.drawer.cancel_btn': 'Hủy bỏ',
    'module.user.action.filter.drawer.reset_btn': 'Huỷ bộ lọc',
    'module.user.action.filter.name': 'Bộ lọc',
    'module.user.action.filter.add_btn': 'Thêm điều kiện',
    'module.user.action.filter.filed_name': 'Bộ lọc',
    'module.user.action.filter.filed_name.email': 'Email',
    'module.user.action.filter.filed_name.id': 'ID người dùng',
    'module.user.action.filter.filed_name.plan_id': 'Gói đăng ký',
    'module.user.action.filter.filed_name.transfer_enable': 'Dung lượng',
    'module.user.action.filter.filed_name.u': 'Tải lên',
    'module.user.action.filter.filed_name.d': 'Tải xuống',
    'module.user.action.filter.filed_name.created_at': 'Thời gian đăng ký',
    'module.user.action.filter.filed_name.expired_at': 'Hạn sử dụng',
    'module.user.action.filter.filed_name.updated_at': 'Hoạt động cuối cùng',
    'module.user.action.filter.filed_name.last_login_at': 'Lần đăng nhập cuối cùng',
    'module.user.action.filter.filed_name.last_login_ip': 'IP đăng nhập lần cuối',
    'module.user.action.filter.filed_name.register_ip': 'Địa chỉ IP đăng ký',
    'module.user.action.filter.filed_name.uuid': 'UUID',
    'module.user.action.filter.filed_name.token': 'TOKEN',
    'module.user.action.filter.filed_name.banned': 'Tình trạng tài khoản',
    'module.user.action.filter.filed_name.invite_by_email': 'Email của người mời',
    'module.user.action.filter.filed_name.invite_user_id': 'ID người mời',
    'module.user.action.filter.filed_name.is_admin': 'Quản trị viên',
    'module.user.action.filter.filed_name.remarks': 'Nhận xét',
    'module.user.action.filter.condition': 'Tình trạng',
    'module.user.action.filter.condition.like': 'Điều kiện',
    'module.user.action.filter.condition.range': 'Phạm vi',
    'module.user.action.filter.value': 'Giá trị',
    'module.user.action.filter.value.placeholder': 'Giá trị',
    'module.user.action.filter.value.in_placeholder': 'Các giá trị được tách bằng dấu phẩy',
    'module.user.action.filter.value.select_placeholder': 'Chọn một giá trị',
    'module.user.action.filter.value.date_placeholder': 'Chọn một ngày',
    'module.user.action.filter.value.option.normal': 'Tài khoản bình thường',
    'module.user.action.filter.value.option.banned': 'Tài khoản bị khóa',
    'module.user.action.filter.value.option.yes': 'Có',
    'module.user.action.filter.value.option.no': 'Không',
    'module.user.action.batch_ban.confirm.title': 'Xác nhận khóa tài khoản',
    'module.user.action.batch_ban.confirm.content': 'Bạn có chắc chắn muốn khóa tài khoản này không?',
    'module.user.action.batch_ban.message.success': 'Đã khóa thành công',
    'module.user.drawer.edit.title': 'Quản lý người dùng',
    'module.user.drawer.edit.message.success': 'Chỉnh sửa thành công',
    'module.user.drawer.edit.ok_btn': 'OK',
    'module.user.drawer.edit.cancel_btn': 'Huỷ bỏ',
    'module.user.drawer.edit.email': 'Email',
    'module.user.drawer.edit.email.placeholder': 'Nhập email của bạn',
    'module.user.drawer.edit.invite_user_id': 'ID người mời',
    'module.user.drawer.edit.invite_user_id.placeholder': 'Nhập ID người mời',
    'module.user.drawer.edit.password': 'Mật khẩu',
    'module.user.drawer.edit.password.placeholder': 'Nếu bạn cần thay đổi mật khẩu, vui lòng nhập',
    'module.user.drawer.edit.balance': 'Số dư tài khoản',
    'module.user.drawer.edit.balance.placeholder': 'Số dư tài khoản',
    'module.user.drawer.edit.commission_balance': 'Số dư hoa hồng',
    'module.user.drawer.edit.commission_balance.placeholder': 'Số dư hoa hồng',
    'module.user.drawer.edit.u': 'Upload',
    'module.user.drawer.edit.u.placeholder': 'Upload',
    'module.user.drawer.edit.d': 'Download',
    'module.user.drawer.edit.d.placeholder': 'Download',
    'module.user.drawer.edit.expired_at': 'Hạn sử dụng',
    'module.user.drawer.edit.expired_at.placeholder': 'Vĩnh viễn',
    'module.user.drawer.edit.plan_id': 'Gói đăng ký',
    'module.user.drawer.edit.plan_id.option.none': 'Không',
    'module.user.drawer.edit.commission_type': 'Loại giảm giá được đề xuất',
    'module.user.drawer.edit.commission_type.option.system': 'Theo hệ thống',
    'module.user.drawer.edit.commission_type.option.cycle': 'Hạ giá',
    'module.user.drawer.edit.commission_type.option.onetime': 'Giảm giá đầu tiên',
    'module.user.drawer.edit.commission_rate': 'Tỷ lệ đề xuất',
    'module.user.drawer.edit.commission_rate.placeholder':
      'Nhập tỷ lệ chiết khấu được đề xuất (để trống, theo dõi trang web để đặt tỷ lệ chiết khấu)',
    'module.user.drawer.edit.discount': 'Phần trăm chiết khấu độc quyền',
    'module.user.drawer.edit.discount.placeholder': 'Nhập tỷ lệ chiết khấu độc quyền',
    'module.user.drawer.edit.discount.tip': 'Sau khi thiết lập, người dùng sẽ luôn được hưởng chiết khấu khi mua bất kỳ gói đăng ký nào',
    'module.user.drawer.edit.is_admin': 'Là quản trị viên',
    'module.user.drawer.edit.is_staff': 'Là nhân viên',
    'module.user.drawer.edit.remarks': 'Nhận xét',
    'module.user.drawer.edit.remarks.placeholder': 'Vui lòng ghi lại tại đây...',
    'module.user.drawer.edit.banned': 'Tình trạng tài khoản',
    'module.user.drawer.edit.banned.option.on': 'Bị ban',
    'module.user.drawer.edit.banned.option.off': 'Bình thường',
    'common.modal.assign_order.modal.title': 'Phân bổ đơn hàng',
    'common.modal.assign_order.message.success': 'Đơn hàng được phân bổ thành công',
    'common.modal.assign_order.email': 'Email người dùng',
    'common.modal.assign_order.plan_id': 'Gói đăng ký',
    'common.modal.assign_order.plan_id.placeholder': 'Chọn gói đăng ký',
    'common.modal.assign_order.price_name': 'Vui lòng chọn thời hạn',
    'common.modal.assign_order.price_name.placeholder': 'Vui lòng chọn thời hạn',
    'common.modal.assign_order.total_amount': 'Số tiền thanh toán',
    'common.modal.assign_order.total_amount.placeholder': 'Nhập số tiền để thanh toán',
    'module.user.action.drop.confirm.title': 'Xóa người dùng',
    'module.user.action.drop.confirm.content': `Bạn có chắc chắn muốn xóa {email} không?`,
    'module.user.action.drop.message.success': 'Đã xóa người dùng thành công',
    'module.user.action.recovery.message.success': 'Người dùng đã được mở khóa tài khoản để dùng bình thường',
    'module.user.action.suspend.message.success': 'Người dùng đã bị tạm khóa tài khoản',
    'module.user.action.reset_secert.confirm.title': 'Đặt lại thông tin bảo mật',
    'module.user.action.reset_secert.confirm.content': `Bạn có chắc chắn muốn đặt lại thông tin bảo mật của {email} không?`,
    'module.user.action.reset_secert.message.success': 'Đặt lại thông tin bảo mật thành công',
    'module.coupon.add_btn': 'Thêm mã giảm giá',
    'module.coupon.list.column.id': '#',
    'module.coupon.list.column.name': 'Tên mã giảm giá',
    'module.coupon.list.column.type': 'Kiểu',
    'module.coupon.list.column.type.amount': 'Số tiền',
    'module.coupon.list.column.type.proportion': 'Phần trăm',
    'module.coupon.list.column.code': 'Mã giảm giá',
    'module.coupon.list.column.limit_use': 'Số lượt dùng',
    'module.coupon.list.column.limit_use.infinite': 'Vô hạn',
    'module.coupon.list.column.valid_period': 'Thời hạn hiệu lực',
    'module.coupon.list.column.action': 'Tuỳ chọn',
    'module.coupon.list.column.action.edit': 'Chỉnh sửa',
    'module.coupon.list.column.action.drop': 'Xóa bỏ',
    'module.coupon.list.column.action.drop.message.success': 'Đã xóa thành công',
    'module.coupon.modal.edit_title': 'Chỉnh sửa mã giảm giá',
    'module.coupon.modal.create_title': 'Mã giảm giá mới',
    'module.coupon.message.edit_success': 'Chỉnh sửa mã giảm giá thành công',
    'module.coupon.message.create_success': 'Đã tạo thành công mã giảm giá mới',
    'module.coupon.modal.name': 'Tên',
    'module.coupon.modal.name.placeholder': 'Vui lòng nhập tên mã giảm giá',
    'module.coupon.modal.code': 'Mã giảm giá',
    'module.coupon.modal.code.placeholder': 'Mã giảm giá có thể tùy chỉnh, để trống sẽ tự động tạo mã',
    'module.coupon.modal.type_value': 'Thông tin giảm giá',
    'module.coupon.modal.value.placeholder': 'Nhập giá trị giảm giá',
    'module.coupon.modal.type.option.amount': 'VND',
    'module.coupon.modal.type.option.proportion': '%',
    'module.coupon.modal.valid_period': 'Thời hạn hiệu lực của mã giảm giá',
    'module.coupon.modal.limit_use': 'Số lần sử dụng tối đa',
    'module.coupon.modal.limit_use.placeholder': 'Giới hạn số lần sử dụng tối đa, khi hết không được sử dụng (để trống nếu không giới hạn)',
    'module.coupon.modal.limit_use_with_user': 'Số lần mỗi người dùng có thể sử dụng',
    'module.coupon.modal.limit_use_with_user.placeholder': 'Giới hạn số lần mỗi người dùng có thể sử dụng (để trống nếu không giới hạn)',
    'module.coupon.modal.limit_plan_ids': 'Gói đăng ký được áp dụng',
    'module.coupon.modal.limit_plan_ids.placeholder': 'Chỉ định gói có thể áp dụng (để trống nếu không giới hạn)',
    'module.coupon.modal.limit_price_ids': 'Chỉ định thời gian đăng ký',
    'module.coupon.modal.limit_price_ids.placeholder': 'Giới hạn khoảng thời gian của đăng ký được chỉ định để sử dụng mã giảm giá (không giới hạn nếu nó trống)',
    'module.coupon.modal.generate_count': 'Mã giảm giá tạo theo số lượng',
    'module.coupon.modal.generate_count.placeholder': 'Nhập số lượng cần tạo theo số lượng lớn',
    'module.order.filter_btn': 'Lọc',
    'module.order.add_btn': 'Thêm đơn hàng',
    'module.order.list.column.trade_no': '#Mã đơn hàng',
    'module.order.list.column.type': 'Kiểu',
    'module.order.list.column.type.new_order': 'Mua mới',
    'module.order.list.column.type.renew': 'Gia hạn',
    'module.order.list.column.type.change': 'Thay đổi',
    'module.order.list.column.type.reset': 'Đặt lại',
    'module.order.list.column.type.onetime': 'Vĩnh viễn',
    'module.order.list.column.type.recharge': 'Nạp tiền',
    'module.order.list.column.plan_id': 'Gói đăng ký',
    'module.order.list.column.price_name': 'Thời hạn',
    'module.order.list.column.total_amount': 'Số tiền thanh toán',
    'module.order.list.column.status': 'Tình trạng đơn hàng',
    'module.order.list.column.status.tip': 'Sau khi được đánh dấu là [Đã thanh toán], đơn hàng sẽ được hệ thống kích hoạt và hoàn thành',
    'module.order.list.column.status.unpaid': 'Chờ thanh toán',
    'module.order.list.column.status.pending': 'Đã thanh toán',
    'module.order.list.column.status.cancelled': 'Đã hủy',
    'module.order.list.column.status.completed': 'Thành công',
    'module.order.list.column.status.discountd': 'Giảm giá',
    'module.order.list.column.status.unpaid.mark': 'Đánh dấu là',
    'module.order.list.column.status.unpaid.mark.pending': 'Đã thanh toán',
    'module.order.list.column.status.unpaid.mark.cancelled': 'Huỷ đơn hàng',
    'module.order.list.column.status.unpaid.mark.message.success': 'Điều chỉnh trạng thái đơn hàng thành công',
    'module.order.list.column.commission_balance': 'Tiền hoa hồng',
    'module.order.list.column.commission_status': 'Tình trạng hoa hồng',
    'module.order.list.column.commission_status.tip':
      'Sau khi được đánh dấu là [Hợp lệ], nó sẽ được hệ thống xử lý và cấp cho người dùng và hoàn thành',
    'module.order.list.column.commission_status.new': 'Được xác nhận',
    'module.order.list.column.commission_status.pending': 'Chờ xử lý',
    'module.order.list.column.commission_status.valid': 'Hợp lệ',
    'module.order.list.column.commission_status.invalid': 'Không hợp lệ',
    'module.order.list.column.commission_status.new.mark': 'Đánh dấu là',
    'module.order.list.column.commission_status.new.mark.valid': 'Hợp lệ',
    'module.order.list.column.commission_status.new.mark.invalid': 'Không hợp lệ',
    'module.order.list.column.commission_status.new.mark.message.success': 'Trạng thái hoa hồng được đánh dấu là thành công',
    'module.order.list.column.created_at': 'Thời gian tạo',
    'module.order.modal.detail.title': 'Thông tin đặt hàng',
    'module.order.modal.detail.email': 'Email',
    'module.order.modal.detail.trade_no': 'Số thứ tự',
    'module.order.modal.detail.price_name': 'Thời hạn',
    'module.order.modal.detail.status': 'Tình trạng đặt hàng',
    'module.order.modal.detail.status.unpaid': 'Chưa thanh toán',
    'module.order.modal.detail.status.pending': 'Đã thanh toán',
    'module.order.modal.detail.status.cancelled': 'Huỷ đơn hàng',
    'module.order.modal.detail.status.completed': 'Đơn hàng thành công',
    'module.order.modal.detail.status.discountd': 'Giảm giá',
    'module.order.modal.detail.plan_id': 'Gói đăng ký',
    'module.order.modal.detail.created_at': 'Thời gian tạo',
    'module.order.modal.detail.updated_at': 'Cập nhật thời gian',
    'module.order.modal.detail.balance_amount': 'Số tiền có sẵn',
    'module.order.modal.detail.discount_amount': 'Số tiền giảm giá',
    'module.order.modal.detail.total_amount': 'Số tiền thanh toán',
    'module.order.modal.detail.callback_no': 'Gateway số đơn',
    'module.order.action.filter.name': 'Tình trạng',
    'module.order.action.filter.add_btn': 'Thêm điều kiện',
    'module.order.action.filter.filed_name': 'Điều kiện',
    'module.order.action.filter.condition': 'Tình trạng',
    'module.order.action.filter.condition.like': 'Giá trị',
    'module.order.action.filter.value': 'Giá trị được lấy ra',
    'module.order.action.filter.value.placeholder': 'Giá trị',
    'module.order.action.filter.drawer.ok_btn': 'Tìm kiếm',
    'module.order.action.filter.drawer.cancel_btn': 'Hủy bỏ',
    'module.order.action.filter.drawer.reset_btn': 'Huỷ bộ lọc',
    'module.order.action.filter.drawer.title': 'Lọc',
    'module.order.action.filter.filed_name.trade_no': 'Số thứ tự',
    'module.order.action.filter.filed_name.status': 'Tình trạng đặt hàng',
    'module.order.action.filter.filed_name.commission_status': 'Tình trạng hoa hồng',
    'module.order.action.filter.filed_name.user_id': 'ID người dùng',
    'module.order.action.filter.filed_name.invite_user_id': 'ID người mời',
    'module.order.action.filter.value.select_placeholder': 'Vui lòng chọn một giá trị',
    'module.order.action.filter.value.status.option.unpaid': 'Chưa thanh toán',
    'module.order.action.filter.value.status.option.pending': 'Đã thanh toán',
    'module.order.action.filter.value.status.option.cancelled': 'Huỷ đơn hàng',
    'module.order.action.filter.value.status.option.completed': 'Đơn hàng thành công',
    'module.order.action.filter.value.commission_status.option.new': 'Mới',
    'module.order.action.filter.value.commission_status.option.pending': 'Đang chờ xử lý',
    'module.order.action.filter.value.commission_status.option.valid': 'Hợp lệ',
    'module.order.action.filter.value.commission_status.option.invalid': 'Không hợp lệ',
    'module.mail_log.list.cloumn.id': 'ID',
    'module.mail_log.list.cloumn.email': 'Email',
    'module.mail_log.list.cloumn.subject': 'Tiêu đề',
    'module.mail_log.list.cloumn.template_name': 'Mẫu',
    'module.mail_log.list.cloumn.error': 'Danh sách lỗi',
    'module.mail_log.list.cloumn.created_at': 'Thời gian gửi',
  }